### ISSUE TITLE
CSS Classname API for CB/MSCB items

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#5212]
## Description
An API for applying CSS classnames to items in Combo Box and Multi-Select Combo Box, for individual styling of dropdown items and MSCB chips.

## Acceptance criteria
- [ ] Item classname generator API:
  - [ ] Java: `setClassNameGenerator(SerializableFunction<T,String>)`
  - [ ] WC/React: `itemClassNameGenerator: ItemClassNameGenerator`
- [ ] Applies classnames to
  - [ ] `vaadin-combo-box-item`s
  - [ ] `vaadin-multi-select-combo-box-item`s
  - [ ] `vaadin-multi-select-combo-box-chip`s

## Code example
Java:
```java
var mscb = new MultiSelectComboBox<Person>();
mscb.setClassNameGenerator(person -> {
  return person.getGender().toString().toLowerCase();
});
```
CSS:
```css
vaadin-multi-select-combo-box-chip, vaadin-multi-select-combo-box-item {
  &.male {
    background: cornflowerblue;
  }
  &.female {
    background: lightpink;
  }
  &.other {
    background: lightgrey;
  }
}
```

## General criteria

- [ ] APIs reviewed 

- [ ] Performance 

- [ ] UX/DX tests in Alpha 

- [ ] Documentation: 

- [ ] How to test? 

- [ ] Limitations: 

## Security
- [x] Security implications have been taken into account (elaborate or link to product security requirement specification if there are implications)
